### PR TITLE
Lycoris loading on Diffusers Backend

### PR DESCRIPTION
**Pull request by AI-Casanova**
Feel free to rename/refactor `KeyConvert` class, I'm bad at naming things. 

Tested on:

- Original Backend
- Diffusers 1.5 LoRA
- Diffusers 1.5 LoCon
- Diffusers 1.5 LoHa
- Diffusers SDXL LoRA
- Diffusers SDXL LoCon
- Diffusers SDXL LoHa

### CODE REVIEW

**Comment by vladmandic** [comment]
this is a massive one, i'll merge to dev and then go over it in details.
one thing i'll refactor is to move conversion to separate file to keep networks.py closer to original.

**Review by vladmandic — COMMENTED** [review]
merging to dev, i'll follow-up with refactoring comments afterwards.

**Comment by AI-Casanova** [comment]
@vladmandic Re: Moving `KeyConvert` et al to a new file:

Named it before I fully new the scope, it's actually a key/module matcher

`convert_diffusers_name_to_compvis` is a misnomer. It simply creates an underscore name map inside the model. It also doesn't have to run every time, only every time backend changes, or sd1.5 to SDXL. It's fast so I doubt it matters.

**Comment by AI-Casanova** [comment]
Everything else should be fairly easy to follow, but I'm available for any questions.

**Pull request merged**
