### PR TITLE
Add support to run as Docker Container

### PR DESCRIPTION
**Pull request by Yoinky3000**
## Description

As #1239 stalled, I would like to create a new PR to add support to build SD Next as a docker image and run it

User can create SD Next container by running ./docker/container.py
with specifying the compute platform they want to use by flag (--compute [cuda, rocm, cpu])
SD Next itself, venv and cache will be saved in volume (can be disabled)

## Environment and Testing

Docker with Windows 11(Nvidia)
Docker with WSL2 Ubuntu(Nvidia)
Tested with Docker 27.0.3

### CODE REVIEW

**Comment by raymanaa** [comment]
Testing compute --cude without volume. simply `python3 ./docker/container.py --compute cuda`
I'm getting: 
image

It might also be interesting to rebase and squash your commits.

**Comment by Yoinky3000** [comment]
> Testing `python3 ./docker/container.py --compute cuda` I'm getting: image
> 
> It might also be interesting to rebase and squash your commits.

are you simply copying the files I added in "docker" folder to your SD Next master branch? If thats in case then it is the reason why --uv is not a valid argument, --uv is just recently added to dev branch and isnt pulled to master yet
If you cloned my docker branch, then there should be no way to get "--uv is invalid" error sd the docker branch is based on the dev branch

**Comment by Yoinky3000** [comment]
seems like i messed it up, maybe i should just create the docker branch again with commiting the files in a single commit

**Comment by raymanaa** [comment]
No! You don't need to! 
You can just pull the main, then use:
`git rebase -i main`
look for a rebase tutorial online, that way you can squash all the commits into a single commit and push again. 

Here's a quick overview about git rebase https://www.youtube.com/watch?v=_UZEXUrj-Ds

**Comment by Yoinky3000** [comment]
> No! You don't need to! You can just pull the main, then use: `git rebase -i main` look for a rebase tutorial online, that way you can squash all the commits into a single commit and push again.
> 
> Here's a quick overview about git rebase https://www.youtube.com/watch?v=_UZEXUrj-Ds

I already recreated the repo, might just use the new repo now

**Pull request closed without merging**
