### PR TITLE
Major lora refactor: SD3.5 Large included

### PR DESCRIPTION
**Pull request by AI-Casanova**
Refactors LoRA loading separately for diffusers backend, eliminates some legacy code

Adds an option to maintain lora backup weights on GPU, trading VRAM for time savings.

Adds a key matcher for SD3.5 Large LoRA trained on KohyaSS 

Draft status until @Disty0 verifies that issues with balanced offload are fixed.

### CODE REVIEW

**Comment by Disty0** [comment]
Relaying the Discord chat here.
Currently, balanced offload works as expected but loading a lora takes very long (3 minutes for a single lora).

**Comment by AI-Casanova** [comment]
Multi LoRA needs to be reimplemented before merge

**Comment by AI-Casanova** [comment]
Multi-LoRA and stepwise weights have been added and tested. 

Confirmed to work on SDXL and SD3.5 large 

@vladmandic possible performance gains to be had under Balanced offload conditions by moving `network_load` inside `processing_diffusers.py` but your knowledge of that code is better than mine.

**Comment by Disty0** [comment]
Offload issues are fixed with: https://github.com/vladmandic/automatic/commit/881fa1183ca3ca1bda1102026155be2b850a9782

**Pull request merged**
