### PR TITLE
Adding notification.mp3 support

### PR DESCRIPTION
**Pull request by DrakeRichards**
## Description

Automatic1111 had a feature that would play a sound if "notification.mp3" was present in the root folder (added in https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/1126). This feature is not present in the vladmandic fork, so this PR re-adds it.

## Notes

I don't know if this feature was intentionally removed or if it just got left out somehow. Please let me know if its removal was intentional.

## Environment and Testing

Release: 3b6effe4
OS: Windows 11
Browser: Firefox 112.0.1 (64-bit)

### CODE REVIEW

**Comment by vladmandic** [comment]
this relies on user to know to upload `notification.mp3` and there is no way to control it.
i removed it because it didn't have any of those done and i hate hard-coded stuff that nobody knows about.if you want to re-add this feature, it needs to be a) configurable, b) disabled by default, c) provide some default sound

**Comment by DrakeRichards** [comment]
That makes sense. It will take some more work to implement that, so I’ll close the PR and resubmit later.

**Comment by joe85** [comment]
@DrakeRichards 

You can add a setting to `shared.py`, I am not sure where is best but `Live Previews` seems okay to me.

```
options_templates.update(options_section(('ui', "Live previews"), {
    "play_sound_on_complete": OptionInfo(False, "Play sound on completion"),
```

Then in `ui.py` reference your setting:

```
if opts.play_sound_on_complete and os.path.exists(os.path.join(script_path, "notification.mp3")):
            audio_notification = gr.Audio(interactive=False, value=os.path.join(script_path, "notification.mp3"), elem_id="audio_notification", visible=False)
```

Here's a royalty free notification sound:
https://pixabay.com/sound-effects/the-notification-email-143029/

**Comment by vladmandic** [comment]
yup. except then there is no need for `os.path.exists` and it should probably go to `/html`, not stay in root.

**Comment by GammelSami** [comment]
Looking forward to this! I already know what sound effect I'll use. 👀 https://youtu.be/Vl3cmacvVm4

**Comment by vladmandic** [comment]
btw, why not keep pr as draft while working on it? when you mark it as ready for review, i'll take a look at it.

**Comment by DrakeRichards** [comment]
> btw, why not keep pr as draft while working on it? when you mark it as ready for review, i'll take a look at it.

I wasn't aware I could do that; thank you! Still learning GitHub.

**Comment by DrakeRichards** [comment]
I've added two settings to the "Live Previews" tab:

- Toggle to enable the notification sound.
- Text box with a path to the sound.

I've also added `html/notification_default.mp3` and the relevant `.gitignore` entries for other .mp3 files.

image

**Comment by brknsoul** [comment]
Thank you, you awesome dudes!

**Comment by TKS4** [comment]
Does this work? Enabled or disabled makes no difference for me.

**Comment by GammelSami** [comment]
> Does this work? Enabled or disabled makes no difference for me.
Yes it works. You have to reload UI (or even better restart the server) after saving the changed setting. 

It is not a real browser Notification. It's just playing a sound using html <audio\>. Maybe your browser blocks playing audio from this tab, but usually browsers auto enable sound playback after you interact with the website once.

**Comment by TKS4** [comment]
>Yes it works. You have to reload UI (or even better restart the server) after saving the changed setting.

Seems there was a commit that 'fixes notification'. And now functions properly 👍

**Pull request merged**
