### PR TITLE
UI-Dropdown Fix

### PR DESCRIPTION
**Pull request by iDeNoh**
## Description
a quick fix to change the selection of upscalers inside SD Upscaler

## Notes

-Changed the radio button input for SD Upscaler to dropdown to fix the upscaler list going off the screen
-added max-width to the dropdown style in sdnext.css to prevent dropdowns from taking up the entire width of the screen, this does not appear to break any other UI elements on desktop or mobile.

## Environment and Testing

Chrome: Linux
Chrome: Android
Safari: (simulated in chrome for android and linux)

### CODE REVIEW

**Comment by vladmandic** [comment]
i think applying `max-width: fit-content;` to entire dropdown might actually make empty dropdowns very bad looking.
perhaps you can move it to actual `ui` or `li` elements of the dropdown (in second or third line in same css?)
if not, then at least do something like `max-width: max(160px, fit-content)` (if that even works in css)

**Comment by iDeNoh** [comment]
fair point, I hadn't thought about empty dropdowns when I tested this. I originally tried it under ui and li but they didn't seem to have an effect.

**Comment by iDeNoh** [comment]
it looks like min(160px, fit-content) does not work, but I think .gradio-dropdown { min-width: 160px; max-width: fit-content } would more or less do the same thing right?

**Comment by vladmandic** [comment]
I think so.

**Comment by iDeNoh** [comment]
Okay, I've went ahead and kept the change inside .gradio-dropdown but I changed it to min-width: 160px; max-width: fit-content;

**Pull request merged**
