### PR TITLE
Add Compel Parsing for SDXL

### PR DESCRIPTION
**Pull request by AI-Casanova**
Adds basic Compel parsing for the SDXL Base Model only.

Refiner currently throws an error.

xyz_grid-0525-sdXL_v10

### CODE REVIEW

**Comment by AI-Casanova** [comment]
@vladmandic I'm not precisely sure what you meant by your second point, but `if "XL" not in pipeline.__class__.__name__:` seems to work well, though just realized I should use a `shared.log` instead of a print for the fail state.

Compel now works for refiner as well, as well as primary/secondary prompt on the base model.

Added the new file because a lot more logic will be needed to enable (weighted prompt:1.1) syntax, and I wanted to keep `processing_diffusers.py` as clean as possible.

**Comment by vladmandic** [comment]
well, `if "XL" not in ...` would also include Kandinsky for example? That's why I'm saying we need a list of pipeline classes that are known as compatibile, not try to guess whats not.

and please, no `print` statements - i tried hard to have unified logging :)

**Comment by AI-Casanova** [comment]
I will absolutely fix the print.

In this framework Kandinsky et al will have to have their own cases, due to singular text encoder etc, however I'm not set up to do massive testing unfortunately, as I'm reliant on Google Colab for all of this.

However we might be able to check the pipeline for number text encoders and unify it that way.

**Comment by vladmandic** [comment]
of course, i don't expect you to test kandinsky! i'm just saying we should have "opt-in" what is supported, not "opt-out" based on "XL" string in class name. and as we test/support additional models in the future, we can add them to "opt-in" list.

**Comment by vladmandic** [comment]
(btw, no need for WIP in title, just mark it as draf in github itself and once its ready remove draft flag)

**Comment by AI-Casanova** [comment]
Imperfectly handles a prompt like `(woman:1.0),` it currently drops the trailing comma

otherwise works as intended
xyz_grid-0531-sdXL_v10

**Comment by vladmandic** [comment]
this looks clean, i'll merge to dev so it can be tested a bit before merging to master.

**Pull request merged**
