### PR TITLE
Improved ROCm installer for Navi 3x and ROCm 5.5+ (and experimental Navi 2x support)

### PR DESCRIPTION
**Pull request by evshiron**
## Description

This PR detects ROCm agents in `installer.py` and set up correct `HIP_VISIBLE_DEVICES` and `HSA_OVERRIDE_GFX_VERSION` environment variables, which should avoid issues caused by not setting up them correctly, enabling a smooth out-of-box experience for Navi 3x users.

This PR also disables the usage of `tensorflow-rocm` for Navi 3x because they aren't supported yet. Revert a previous change from https://github.com/vladmandic/automatic/issues/1929 as well.

Experimental support for Navi 2x is added too, but I haven't tested it.

## How does it work?

We will firstly find out all ROCm agents via `rocm_agent_enumerator`.

Use the first available Navi 3x/2x dGPU to set up `HIP_VISIBLE_DEVICES`, which makes the app see only one GPU that works, so that unsupported GPUs aren't used and will not be overrided incorrectly later, both of which might lead to some sort of core dump. `HIP_VISIBLE_DEVICES` is not set when no device matches our list, and can be overwritten by explicitly setting it.

Also, `HSA_OVERRIDE_GFX_VERSION` is automatically configured for Navi 3x/2x device if it is found in the previous step, to avoid HIP to incorrectly recognize our GPU, thus avoid another source of core dump. It won't be set if conditions fail to meet, and can be overwritten explicitly.

Then we read ROCm version from `hipconfig --version`. If it's ROCm 5.5+, the officially built `torch` nightly will be installed for best performance and compatibility. If not, fallback to the original behavior: use `torch` built for ROCm 5.4.2.

## Notes

AMD GPUs other than Navi 3x and Navi 2x are not considered in this PR, because they might just work. Let's add more in the future.

## Environment and Testing

Developed on Ubuntu 22.04, with ROCm 5.6 installed.

Hardware: 7800X3D (gfx1036) + RX 7900 XTX (gfx1100)

Tested in host environment and Docker environment with ROCm 5.6 installed.

There was an attempt https://github.com/vladmandic/automatic/pull/1972. @Aptronymist would you mind helping me test if this works on your end?

```bash
git clone https://github.com/are-we-gfx1100-yet/automatic/tree/merge/rocm_installer_for_navi
cd automatic
./webui.sh --debug
```

### CODE REVIEW

**Comment by vladmandic** [comment]
Two comments:
- Both subprocess calls should be in try/except blocks with some defaults if failing.
- I prefer not to use pipe or anything advanced in run calls as not all shells may work nicely - can you remove grep and do it in python instead, that's just one liner.

**Comment by Aptronymist** [comment]
> There was an attempt https://github.com/vladmandic/automatic/pull/1972. @Aptronymist would you mind helping me test if this works on your end?

Oh, crap, sorry! 
Didn't see this until just now, mostly "off" today. I'll check it out!

**Comment by evshiron** [comment]
@Aptronymist 

No worries!

**Comment by vladmandic** [comment]
i'm merging this pr as-is and when second one with `HSA_OVERRIDE_GFX_VERSION` is ready, i'll add that as well.

**Pull request merged**
