### PR TITLE
Style Controlnet Controls

### PR DESCRIPTION
**Pull request by DrJKL**
## Description

More vertical alignment, creates a grid of options for the radio buttons.

## Notes

Depends on the classes/ids in https://github.com/Mikubill/sd-webui-controlnet/pull/1449

## Environment and Testing

Windows 10

### CODE REVIEW

**Comment by vladmandic** [comment]
with any visual change, can you do a screenshot before/after?

**Comment by DrJKL** [comment]
Definitely 🙂

## Before
image


## After
image

**Comment by vladmandic** [comment]
i like it, but if i'm nitpicking - can you place control weight on its own line so start/end steps are on the same line? makes more sense to group them that way

**Comment by DrJKL** [comment]
> i like it, but if i'm nitpicking - can you place control weight on its own line so start/end steps are on the same line? makes more sense to group them that way

That should be doable, sure.

**Comment by vladmandic** [comment]
perfect, then i'll wait for update before merging.

**Comment by DrJKL** [comment]
## Updated
image

**Comment by DrJKL** [comment]
## Updated
image

**Comment by vladmandic** [comment]
approved pending required upstream changes in <https://github.com/Mikubill/sd-webui-controlnet/pull/1449>

**Comment by DrJKL** [comment]
image

**Comment by DrJKL** [comment]
No specific reason, no.

It doesn't currently have any styles provided. Want me to propose a PR there too?

**Pull request merged**
