### PR TITLE
Conditional logger

### PR DESCRIPTION
**Pull request by midcoastal**
- Adds ability to get wrapped logger based on the existence of an ENV flag
- Adds ability to wrap a logger with a prefix

Why?

ENV. Instead of:
```
debug = os.environ.get('SD_EN_DEBUG', None) != None

if debug:
    shared.log('Extra Networks: some message')
```

A more concise version will do:
```
debug_log = shared.log.env('SD_EN_DEBUG').prefix('Extra Networks: ')

debug_log.info('some message')
```

This will have two effects:
- It will encourage more debug reporting, because it can be selectively turned on, and thus "excess" reporting will be a non-issue.
- It will get rid of all of the `# shared.log('Some message that a dev once needed, but now doesn\'t, but also doesn\'t want to delete')`

The prefixing portion is just a nicety.

### CODE REVIEW

**Comment by vladmandic** [comment]
i'm ok with this, but can you add example usage in comments of the code itself?

**Comment by vladmandic** [comment]
i just saw latest modifications, i don't understand where this is going?

```python
# Backward compat until existing referenced get cleaned
import logging
from logging import print_dict, log
from profiling import print_profile
import modules.logging as logging
from modules.logging import print_dict, log
from modules.profiling import print_profile
```

this looks like possible refactoring `installer.py` which is out-of-scope here.
lets focus on embeddings loader as that actually makes a big impact? isolate changes there so modelloader and installer changes are not tied to it and we'll review that.

**Comment by midcoastal** [comment]
Yeah, I can see that. Thanks for the draft. I will round back to this. It's not so much and `installer.py` reactor as it is breaking things out into their own files for the sake of isolation.

I occasionally run into circular dependencies (you'll see another PR with regards to that as well in a bit), and in broke these things out for that purpose.

In my mind, having too many things that aren't always all needed together as risky. I'm as guilty of it as the next. I needed access to logger inside something that was called inside of installer (at some point), so it made sense to break log out to it's own thing so i could include a finished module without killing python. 

The specific includes at the top are to maintain backwards combat with other code that still expects those things to be in installer. I did that to avoid a sweeping refactor.

But again, I'll come back to this.

**Comment by vladmandic** [comment]
i took a quick look at the latest version of the pr and its massive and extremely verbose and possibly over-engineered, i'm just not sure that logger deserves 500+ loc.  

and at the end, functionality is nearly the same to existing one-liner that can be used in any module.  
example:  
`debug = shared.log.debugif os.environ.get('SD_XXX_DEBUG', None) is not None else lambda *args, **kwargs: None`

**Comment by midcoastal** [comment]
> i took a quick look at the latest version of the pr and its massive and extremely verbose and possibly over-engineered, i'm just not sure that logger deserves 500+ loc.  
> 
> and at the end, functionality is nearly the same to existing one-liner that can be used in any module.  
> example:  
> `debug = shared.log.debugif os.environ.get('SD_XXX_DEBUG', None) is not None else lambda *args, **kwargs: None`
> 

Fair. The PR is 3 and change, most of which is examples, comments, and the profiler move/decorator. The actual meat is <200 loc, and it does more than just replace the if/lambda.

For me, when I was developing/debugging, the sugar certainly lowered the mental costs and made me more likely to add verbose debugging that definitely helped and I would have been more likely to keep in for future adventurers.

But it's pulled out of the other PRs, so I suppose it's your call now.

**Comment by jhcuarta** [comment]
Hi
Pardon my lack of expertise, but the debugging steps are 500?

06:36:09-989168 INFO     Startup time: 16.73 { torch=3.37 gradio=0.95           
                         diffusers=0.15 libraries=3.39 extensions=2.29          
                         models=3.12 face-restore=0.23 upscalers=0.07           
                         ui-extra-networks=0.32 ui-txt2img=0.11 ui-img2img=0.14 
                         ui-settings=0.32 ui-extensions=0.87 ui-defaults=0.11   
                         launch=0.66 api=0.15 app-started=0.35 }                
06:38:00-108891 DEBUG    Server: alive=True jobs=0 requests=2 uptime=122        
                         memory=1.19/31.22 backend=Backend.ORIGINAL state=idle  
06:40:00-231022 DEBUG    Server: alive=True jobs=0 requests=2 uptime=242        
                         memory=1.19/31.22 backend=Backend.ORIGINAL state=idle  
06:42:00-352700 DEBUG    Server: alive=True jobs=0 requests=2 uptime=362        
                         memory=1.19/31.22 backend=Backend.ORIGINAL state=idle

**Comment by vladmandic** [comment]
at the end, i went with a simpler approach. newly defined log level trace
and each module can use it by setting something like:

> trace = shared.log.trace if os.environ.get('SD_CONTROL_DEBUG', None) is not None else lambda *args, **kwargs: None

main problem i have with conditional logger as implemented here is that env is checked for each log call and it has a complete reimplementation of logger class with all standard levels - there is just no need for that.

**Comment by midcoastal** [comment]
> main problem i have with conditional logger as implemented here is that env is checked for each log call and it has a complete reimplementation of logger class with all standard levels - there is just no need for that.

It actually doesn't, it returns a stand-alone logger that always evaluates as false.  That said, I'll have a look at trace.

My concern with `trace` is that it doesn't actually solve the problem at hand:  yes, it adds an additional logging level above `debug` but beyond that, what does it do?  The implementation (the whole `log.trace if condition else lambda` nonsense) is exactly the same, and, if you are going to do that anyway, you may as well forego the whole `trace` bit, as there is no difference.

As implemented in this PR, you can conditionally enable *all* of the associated log levels (conditional on the env var, and call whatever type you want).

As for re-defining all of the log functions, that wasn't necessary, and was only in there for convenience at some point when I was developing, and can be easily removed.

**Comment by midcoastal** [comment]
I still think my goals have legs, so I will have a look at the implementation and bring it down a peg for that end.

**Comment by midcoastal** [comment]
@vladmandic - Kind of a silly `git` question: Is it acceptable to merge `dev` **in** to this branch to keep it up to date?  The other few branches I have been working on I have stashed my changes, made a new branch of the same name based of latest dev, and applied my changes there, so as to keep the commit history cleaner.  This requires a push force, and it's weird...  lol

Should i just merge current dev in?  Is that the best way?

**Comment by vladmandic** [comment]
in most cases, yes. but it really depends on conflicts.

**Pull request closed without merging**
