### PR TITLE
Save merge recipe

### PR DESCRIPTION
**Pull request by vladmandic**
<https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9312>

### CODE REVIEW

**Comment by vladmandic** [comment]
@space-nuko any chance you might create a new pr or update this one so there is no merge conflict? if not, i'll have to go through conflict resolution during merge and its messy since pr originated for a different fork.

**Comment by space-nuko** [comment]
Hi I saw your mails, I can get back to my dev box in a week or so, sorry about that

**Comment by vladmandic** [comment]
No worries, I'd rather wait for you as value contributor than force things...

**Comment by vladmandic** [comment]
merged manually.

**Pull request closed without merging**
