### PR TITLE
Add ngrok support

### PR DESCRIPTION
**Pull request by dwu11**
## Description

Add support to access ui remotely through ngrok.

## Notes

Uses the ngrok-py  implementation from Automatic1111's webui with some small alterations to the library installation. Same command line args.

## Environment and Testing

Windows 11 Pro, Python 3.10

### CODE REVIEW

**Comment by vladmandic** [comment]
problem with ngrok is supportability - if i merge this pr, then it becomes a supported solution and i have no chance of providing support since neither me or any of the active devs have ever worked with ngrok. unless you wish that i assign every future ngrok related issue to you?

**Comment by tcmaps** [comment]
But does it really have to be integrated? Set up ngrok are 2 commands, and 1 to run it.

**Comment by vladmandic** [comment]
how well does it work? do ui components render correctly? refresh correctly? what about actual execution?
i have no way to run any tests.

**Comment by tcmaps** [comment]
I used ngrok on sagemaker and hadn't anything to complain so far, seems even faster than cloudflared. Only caveat may be the session limit of 1h with a free plan. It's quick to setup, `pip install pyngrok` will provide the ngrok binary in a shell also.

**Comment by vladmandic** [comment]
i get what you're saying, but please understand what i'm saying - i have no idea about ngrok and unless someone is willing to own that, i'm not merging. but like i said, this would be near-trivial to write as an extension - why not do that?

**Comment by tcmaps** [comment]
oh actually my initial question was more directed at op, whether integration/extension into the repo are even required, because it's simple enough to use as standalone package.

**Comment by florianperrenet** [comment]
> oh actually my initial question was more directed at op, whether integration/extension into the repo are even required, because it's simple enough to use as standalone package.

True it's as simple as:
```bash
pip install pyngrok
ngrok config add-authtoken <YOUR_AUTHTOKEN>
ngrok http 7860
```

**Comment by HashedViking** [comment]
<html>
<body>
<p style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: #3b82f680; --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; margin-top: ; margin-right: ; margin-bottom: var(--ifm-leading); margin-left: ; color: rgb(89, 89, 89); font-family: EuclidSquare, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Resources included for free, Ngrok:</p>

Resource | Limit on Free
-- | --
Users | 1
Active Endpoints1 | 1
ngrok static domain | 1
Tunnels per agent | up to 3
Bandwidth | 1 GB/month
TCP Connection Rate | 120/min
Agents | 1
Edges | 1
Logs/Events | Up to 10,000 per month
OAuth/OIDC MAU | Up to 5 per month
HTTP Requests | Up to 100,000/month
Webhook verifications | Up to 500/month


</body>
</html>

1 GB/month of bandwidth is not nearly enough for stable diffusion operations, [frp](https://github.com/fatedier/frp) integration would be awesome as a self-hosted option

**Comment by vladmandic** [comment]
moving status to draft until maintainer is found.

**Comment by vladmandic** [comment]
a year later and nobody volunteered so closing the pr. i cannot merge something i never tried in my life and be expected to maintain it myself.

**Pull request closed without merging**
