### PR TITLE
Add DirectML backend.

### PR DESCRIPTION
**Pull request by lshqqytiger**
## Description

Add DirectML backend for who is unable to use CUDA and ROCm both. (AMDGPU on Windows, Intel GPUs, etc)
The only requirement for DirectML is to support DirectX12.

## Notes

- DirectML does not provide important vram informations. So we need to estimate/get from gpu drivers.
- VRAM estimation is currently available for AMDGPUs. I couldn't find a tool to monitor Intel GPUs yet.
- DirectML backend has some problems like mps device. (actually, they share 1~2 problem(s))

## Environment and Testing

Windows 11
Python 3.10.11
PyTorch 2.0.0+cpu
torch-directml 0.2.0.dev230426
screenshot 2023-04-30 014417

### CODE REVIEW

**Comment by anapnoe** [comment]
this is great you are here, thank you for this we hope that you join our team! 
my discord Eoan#9885 and Vlads vlado#8083

**Comment by vladmandic** [comment]
> this is great you are here, thank you for this we hope that you join our team!

I'll setup a discord server soon, i have all of you in DMs at the moment :)

**Comment by BinaryQuantumSoul** [comment]
Does that mean that the three major a1111 forks work together ?

**Comment by vladmandic** [comment]
> Does that mean that the three major a1111 forks work together ?

And few more - thats the plan :)

> Btw, a discord server with all the development updates would be awesome

Its comming :)

**Pull request merged**
