### PR TITLE
Implement Duplicate Extension Check in 'install_extensions()' Function

### PR DESCRIPTION
**Pull request by SOELexicon**
Hey Bro,

figured I go scratch this one off your backlog ;) 

Title: Implement Duplicate Extension Check in install_extensions() Function

Description:

In this change, I have added functionality to the install_extensions() function in order to check for and log any duplicate extensions found across both the built-in and custom extensions directories.

This addition provides a level of error checking and prevents potential conflicts between extensions with the same name located in different directories. The function now maintains a dictionary of all encountered extensions, and logs any duplicates in a single line, separated by commas, at the end of the function execution.

This enhancement can help in debugging issues related to extension installations, such as unexpected behavior, crashes, or incorrect data being returned. By providing visibility into duplicate extensions, developers can more quickly identify and resolve these issues, resulting in a more robust and reliable application.

Moreover, logging duplicate extensions can be an important step in maintaining extension hygiene and ensuring the correct loading and running of extensions. This may be particularly helpful in environments with a large number of extensions or frequent updates and changes to extensions.

This change does not affect the existing functionality of installing and updating extensions. It remains fully backward-compatible with previous code and usage patterns.

Testing:
Tested on Windows but the changes are basic so shouldn't incur any issues on other OS's

### CODE REVIEW

**Review by vladmandic — COMMENTED** [review]
update logic

**Review by vladmandic — COMMENTED** [review]
updated logic

**Review by vladmandic — CHANGES_REQUESTED** [review]
update logic

**Comment by SOELexicon** [comment]
Tested those changes.

`22:24:31-038405 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'a1111-stable-diffusion-webui-vram-estimator', 'deforum-for-automatic1111-webui', 'gif2gif',
                         'infinite-zoom-automatic1111-webui', 'sd-3dmodel-loader', 'sd-dynamic-prompts',
                         'sd-infinity-grid-generator-script', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-aspect-ratio-helper', 'sd-webui-photopea-embed', 'sd-webui-supermerger',
                         'sd-webui-text2video', 'stable-diffusion-webui-chatgpt-utilities-main',
                         'Stable-Diffusion-Webui-Civitai-Helper-main', 'stable-diffusion-webui-wildcards',
                         'video_loopback_for_webui']
22:24:31-041409 WARNING  Extensions duplicates: ['stable-diffusion-webui-rembg']`

looks good buddy :) will hopefully help when people post their logs

**Pull request merged**
