### PR TITLE
Simple Dockerfile and Container YAML with no Volumes

### PR DESCRIPTION
**Pull request by EntropyFails**
## Description

Recently, someone attempted a patch with a Dockerfile that was fairly specific to their needs. I just wanted to create a simplified container with minimal requirements that works on the core directory installed on the machine instead of doing all the weird volume mounting and re-cloning of the repo of the previous one that was posted.

## Notes

I stuck with the simplest possible system that I think would work with the least opinions on the system possible. It has 2 args
- UID for setting specific userID's for various Docker environments if needed
- INSTALLDIR for picking where the files go

Because of Docker, I had to use an ENV var in the EXEC entrypoint to allow for changes to the Installation directory.

I don't do any pip caching so subsequent runs take the full time as I am using this for HuggingFace spaces and they don't save docker files between runs.

It's the most generic thing I could think of that works but would be happy to patch if someone can think of more general solution. As it stands, you can just ```docker compose build``` and ```docker compose up``` if you have the Docker and Nvidia link all set up on your box and it works.  For that, I removed the input part of sd_models.py so it loads at least one model without any user input (which obviously isn't available in the container entry script).

## Environment and Testing

Windows 10, Docker 23.0.5

### CODE REVIEW

**Comment by vladmandic** [comment]
> ENV LD_PRELOAD=libtcmalloc.so

This is heavily opinionated. I love libtcmalloc, but its not for everyone and should not be forced by default.

Also, don't patch sd_models.py, that is part of core repo. Instead force that `--ckpt <path-to-model>` should be passed to docker container to load a specific model. Model should never reside inside container.

**Comment by EntropyFails** [comment]
Sounds good! 

Yeah, I didn't even notice the thread-safe malloc honestly. ;) I'll set that as an optional parameter only.

I'll remove the sd_model.py changes and have it pass checkpoints directly.

Thanks for the feedback!

**Comment by vladmandic** [comment]
any updates?

**Comment by vladmandic** [comment]
closing in favor of #1239

**Pull request closed without merging**
