### PR TITLE
Fix training with up-to-date dependencies and add SD-XL LoRA training support

### PR DESCRIPTION
**Pull request by evshiron**
## Description

Update submodule in `modules/lora` to the dev branch of https://github.com/kohya-ss/sd-scripts. So that we don't need to downgrade `diffusers` before training anymore.

Fix LoRA/LyCORIS training integration.

Add SD-XL LoRA training integration.

Save LoRAs as `safetensors` by default, to allow direct use in Diffusers.

Maybe we should add an argument for `process.target_size`.

## Notes

Please generate images with a resolution of 1024x1024 for best results in SD-XL.

## Environment and Testing

Developed on Ubuntu 22.04, with ROCm 5.6 installed.

Hardware: 7800X3D (gfx1036) + RX 7900 XTX (gfx1100)

Tested in host environment.

### CODE REVIEW

**Comment by vladmandic** [comment]
nice one - but perhaps a quick reach-out to kohya to check when he's planning to merge dev to main?

**Comment by vladmandic** [comment]
i've marked the pr as draft as thats what subject line said - convert to 'ready for review' when its ready.

**Comment by vladmandic** [comment]
this pr is still marked as draft - is it ready? let me know and i'll review & merge to dev...

**Comment by evshiron** [comment]
Yeah. Upstream hasn't been merged to the main branch yet.

It's been a long time and I am currently busy. As a result, this PR might not be updated in time.

**Comment by vladmandic** [comment]
i've implemented the changes, but had to do it manually since there were too many other changes to `train.py` in progress.
anyhow, thanks for the contribution - i'll add a note to changelog!
changes are in dev branch.

**Pull request closed without merging**
