### PR TITLE
fix(extras): fix batch image processing on 'Extras\Batch Process' tab

### PR DESCRIPTION
**Pull request by vladmandic**
<https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9513>

### CODE REVIEW

**Comment by myndxero** [comment]
Speaking of batches.... If I have identical settings, Vlad's UI will crash on batch size 50, but auto's still works fine, I've done as high as 80 or something, all 512x512, just for teh funsies. HOWEVER, I noticed vlad's uses less vram. I am guessing that's just the difference between torch 2.0 and previous on auto1111.

Not sure if issue is worth a peak, I certainly don't care, just wanted to report it as a point of interest.

**Comment by vladmandic** [comment]
applied as patch from cli, closing the pr.

**Comment by myndxero** [comment]
Sounds good. This also fix the Ui failing to launch? I updated minutes
after one of your commits this morning, and haven't been able to launch
since haha.

**Comment by vladmandic** [comment]
> This also fix the Ui failing to launch?

first i've heard of it. check if there is a problem in latest version and report if there are any problems.

**Comment by myndxero** [comment]
This is all I am getting.

image

It struck me that when I updated earlier, I was also trying to update kdiffusers, wanted to try the "fix" to see how it worked by manually editing the code, that maybe I was interrupted the git pull process since it doesn't like to work against modified files different from the record. Troubleshot that, restored originals but still failing to get any further than above screenshot.

**Comment by vladmandic** [comment]
it shouldn't be related. and i've never seen this.
if the last line is `Torch 2.0.0+cu118`, it makes no sense, after that there are some trivial print statements that should be printed as well:

```python
        log.info(f'Torch {torch.__version__}') <--- this is what you see
        if not torch.cuda.is_available():
            log.warning("Torch repoorts CUDA not available")
        else:
            if torch.version.cuda:
                log.info(f'Torch backend: nVidia CUDA {torch.version.cuda} cuDNN {torch.backends.cudnn.version()}')
            elif torch.version.hip:
                log.info(f'Torch backend: AMD ROCm HIP {torch.version.hip}')
            else:
                log.warning('Unknown Torch backend')
```
unless torch itself crashes when accessing `not torch.cuda.is_available()` and that is hidden in except statement.

**Comment by myndxero** [comment]
I'm working on a fresh install atm on another drive since I don't like not having at least one working installation haha.

See how it goes. I had a crash before I updated earlier that had some lingering processes opened that may have been interfering, will restart and report back as soon as the new installation finishes building venv.

**Comment by vladmandic** [comment]
i've just added few extra messages if something goes wrong in that part of the code instead of silent exit.

**Comment by myndxero** [comment]
Crisis adverted, something lingering in the processes was holding me up, a full restart of the computer fixed it.

**Comment by myndxero** [comment]
> i've just added few extra messages if something goes wrong in that part of the code instead of silent exit.

Sorry to divert your attention.

**Comment by myndxero** [comment]
I'm not sure where best to just leave you a casual thing that may or may not have anything to do with anything, but for some reason in the txt2img tab clip skip set to 1, but in the stable diffusion settings it was set to 2. It's probably nothing noteworthy, but see something say something I guess?

**Pull request closed without merging**
