### PR TITLE
Optional repurpose batch mode for frames

### PR DESCRIPTION
**Pull request by Symbiomatrix**
## Description

Currently, when process_batch is supplied with batch_size > 1, it will loop over all images, duplicate each one and perform a standard run with a sequential seed. IMO, this is a mostly useless feature. A much more demanded feature recently is video processing, or possibly iterating over frames. I propose batch mode be used to process multiple frames at a time according to batch_size with a fixed seed. Or at least, wrap this in a setting so that extensions can make use of it.

## Notes

The seed / subseed have been patched to single values by forcing a list structure prematurely. It'd be more elegant to have processing make the decision (based on said setting).
There are a handful more improvements which can be made to this function, for example the `read_from_image` and `images.save_image` at the end may need to handle more output formats. But a basic batch run works.

### CODE REVIEW

**Comment by vladmandic** [comment]
thats actually not a bad suggestion. i'll review pr in details as it will require some tweaks before it can be merged.

**Comment by Symbiomatrix** [comment]
Glad to have you on board, let me know if I can help.

**Comment by Symbiomatrix** [comment]
Have you had a chance to review it, vlad? As indicated in #2232 the current method in infv2v is quite a whopper of a hack, essentially reconstructing the whole 1,6 forward with just a handful of lines altered to my understanding (admittedly a very limited one in this case). I think this method should provide the higher level control needed.

**Comment by vladmandic** [comment]
conceptually, no issues. and minor nitpicks i have about the code i can change post-merge.
my main concern is impact on all workflows - is there impact used with other extensions for example?

**Comment by Symbiomatrix** [comment]
Theoretically, if any extension (or person) specifically uses batch mode as a simple replacement for running multiple gens on a bunch of images, then that would break their flow since the output is completely different. Also, different images which don't have the same dimensions or other variations may also not work well, shape mismatch errors are definitely a concern. I use relatively few extensions, can't say I've seen any targeting batch mode specifically though.
Nevertheless, that's why I proposed that this modified usage could be triggered only when a certain setting is checked (off by default) - that way extensions or users which specifically need frame batching can make use of it with a temporary switch.
I haven't added settings to the main repo before, so might have erred on this, let me know if it's correct.

Correction: It most definitely errs for different dimensions, getting some message about "inhomogeneous shape". I believe an additional setting would be prudent as such.

**Comment by vladmandic** [comment]
that makes sense as all images in batch should be same size by definition.
and i'm ok with this concept now that its user selectable. i just need to find some time to properly review.

**Comment by Symbiomatrix** [comment]
Thanks, no rush. I'm only part time tinkerer myself so whenever it's convenient, all the same.
It seems to be working correctly on my end with both t / f and batch 1 / 2. Apart from all the temp files gradio keeps dumping around in batch, these are quite irritating.

**Comment by Symbiomatrix** [comment]
Hello @vladmandic , thanks for merging.
I've added a simple (multi) video frame extraction and merging with imageio (no audio) to the workflow, couple functions with ~50 lines.
I'm oscillating between whether it's more of an extension's feature or a complement for frame mode to make it more "batteries included". However, given that there's no mapping from serial input images to output apart from `images.save_image`'s return value (as far as I know), or callbacks in process_batch, I'm leaning a bit towards adding that as being the less twisted path.
What do you think - would that be appropriate, or should callbacks be used (existing ones or added)?
I'm still not sure how best to structure the connection between frames.

**Comment by vladmandic** [comment]
yeah, that sounds like an extension.
but if you need some additional callbacks added to core to support your workflow, i have no problem with that. just make sure that existing ones are really insufficient.

**Comment by Symbiomatrix** [comment]
Alright, thanks. I'll try to work something else out.

**Pull request merged**
