### PR TITLE
k-diffusion update

### PR DESCRIPTION
**Pull request by sdbds**
## Description

see hee https://github.com/vladmandic/automatic/issues/395

## Notes

change install fork

## Environment and Testing

windows 10

### CODE REVIEW

**Comment by vladmandic** [comment]
my concern is that crowsonkb is official one - will wywywywy be maintained in the long-run? what if there are updates to crowsonkb? and why are fixes from wywywywy not submited to crowsonkb?

also, changing line in setup.py would only impact fresh installs, any existing installs would not be updated. and rehosting origin in existing install is messy at best.

**Comment by sdbds** [comment]
> my concern is that crowsonkb is official one - will wywywywy be maintained in the long-run? what if there are updates to crowsonkb? and why are fixes from wywywywy not submited to crowsonkb?
> 
> also, changing line in setup.py would only impact fresh installs, any existing installs would not be updated. and rehosting origin in existing install is messy at best.

they metion this in here.
https://github.com/crowsonkb/k-diffusion/issues/56
it seems that crowsonkb is sick so maybe we will wait for a long time.

**Comment by vladmandic** [comment]
> I need to look at this but I'm sick right now so it might be a few days

but he is at least responsive, not missing in action, lets give him a chance for a bit longer and if nothing happens, then we can switch.

**Comment by sdbds** [comment]
> > I need to look at this but I'm sick right now so it might be a few days
> 
> but he is at least responsive, not missing in action, lets give him a chance for a bit longer and if nothing happens, then we can switch.

Let's put it aside for now, and we'll check here again next month.

**Comment by tusharbhutt** [comment]
> > I need to look at this but I'm sick right now so it might be a few days
> 
> but he is at least responsive, not missing in action, lets give him a chance for a bit longer and if nothing happens, then we can switch.

Katherine is awesome, she's pretty responsive on Twitter so if she's sick, hopefully it's not something too bad.

**Comment by nekoworkshop** [comment]
_If_ this change was to be accepted, I would propose adding it as a new sampler rather than replacing the existing ones. 

The author of the change has not provided any qualitative analysis of the "improvement" and has made it clear that he came up with this by playing with the code by switching variables around without knowing the math. The x/y plot he posted does show an improvement of very low step values but the converged output also changes in a way that I consider being subjective. 

What's more concerning is some people have reported getting way less detail with the proposed change. See
https://github.com/crowsonkb/k-diffusion/issues/56#issuecomment-1520489240 

Here is another example of the loss of detail. The commenter even posted it as a proof that the fix works but to me the original sampler results looks way better than the "fix"
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8457#discussioncomment-5562223

**Comment by hiss-remi** [comment]
> What's more concerning is some people have reported getting way less detail with the proposed change. See [crowsonkb/k-diffusion#56 (comment)](https://github.com/crowsonkb/k-diffusion/issues/56#issuecomment-1520489240)

The 'soft focus' effect is definitely real, at least in my experiments with DPM ++ 2M. The 'TestX' variant reduces that, but I'm not finding it to be a real improvement over the base sampler, which the test version was at least sometimes.

**Comment by LiteSoul** [comment]
I believe this fix is without a doubt a great improvement, so I would definitely recommend it to have it.
The washed out effect could be minimized with a VAE like kl-f8-anime2.

Since it's not official, I agree that we could add it as a "new" sampler.

**Comment by Panchvzluck** [comment]
I feel new samplers would be ideal as well, since it is good for DPM++ 2M Karras, but for DPM++ 2M you will get very washed out colors, even if using a saturated VAE.

**Comment by sdbds** [comment]
> _If_ this change was to be accepted, I would propose adding it as a new sampler rather than replacing the existing ones.
> 
> The author of the change has not provided any quantitative analysis of the "improvement" and has made it clear that he came up with this by playing with the code by switching variables around without knowing the math. The x/y plot he posted does show an improvement of very low step values but the converged output also changes in a way that I consider being subjective.
> 
> What's more concerning is some people have reported getting way less detail with the proposed change. See [crowsonkb/k-diffusion#56 (comment)](https://github.com/crowsonkb/k-diffusion/issues/56#issuecomment-1520489240)
> 
> Here is another example of the loss of detail. The commenter even posted it as a proof that the fix works but to me the original sampler results looks way better than the "fix" [AUTOMATIC1111#8457 (comment)](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8457#discussioncomment-5562223)
> 
> Bottom line is I'm all open to try out new samplers, but I don't think the proposed change is tested enough to be accepted as an _improvement_ to the existing sampler, which is based on published paper and have clearly proof of their performance.

It seems to have happened in tests without using Karras, more tests can be done to see the results.

**Comment by Cleorious** [comment]
Any update on this alternative sampler? Cmiiw but is the sampler being talked about in this thread the same with the one mentioned [here?](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8457) Would be great if we could have it as a separate sampler as well.

**Comment by sdbds** [comment]
> Any update on this alternative sampler? Cmiiw but is the sampler being talked about in this thread the same with the one mentioned [here?](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8457) Would be great if we could have it as a separate sampler as well.

The current issue is that the original repository author has fallen ill, and frequent changes to the repository can greatly impact stability. We must at least wait for external code updates before we can continue modifying the code, such as turning it into a separate variant sampler.

We hope for her recovery and to review the code changes afterward.

**Comment by sdbds** [comment]
i find [crowsonkb](https://github.com/crowsonkb) is coming back, so we can close this :)

**Pull request closed without merging**
