### PR TITLE
Settings Tab Improvements

### PR DESCRIPTION
**Pull request by Gegell**
## Description

Some minor improvements to the settings page:
- Made spacing between items more consistent. The boolean check-boxes were nudged to the bottom, should be more even now.
- Added an indicator left to the individual setting items when the changed value was not applied yet. When the indicator is clicked it will restore the previous value.
- Added a top-level indicator on each tab, which is active whenever there are unapplied changes in the setting tab. Similarly to the indicators for the individual settings, it resets all settings in the corresponding tab when clicked.
- The indicators also show when a value is not yet stored in the settings file (e.g. when a new extension is installed it should show the new settings which get stored with the next run of "Apply settings").
Likewise for tabs which contain such settings.
- Made the first item of the settings group (settings on the right) line up with the uppermost tab header of the setting tabs to the left.
- Made empty space right of check-boxes not clickable (suggested by EfourC: https://github.com/vladmandic/automatic/pull/638#issuecomment-1529416054)
- When not enough space is available horizontally, the setting tabs will be moved above the actual settings, such that the settings have more horizontal space to work with.

## Notes

- [x] Seems to still have issues with checkbox groups (when toggling back to the previous values) it does not realize no changes need to be made, and marks it as a changed setting.
- [x] The setting groups should also get an indicator such that it's visible at a glance whether a change in one of those groups is still not applied.
- [x] Currently the modification indicator uses just css to insert an empty element via the pseudo `::before` selector. While this works it is not best practice to insert content via those selectors (due to accessibility issues). Might need to actually add an additional html element in `create_setting_component()` in [modules/ui.py](https://github.com/Gegell/automatic/blob/2c5ec7ce0b9d58f85d233e6c87642e369f7c1717/modules/ui.py#L1197).
- [x] Additional feature for the indicators: Clicking on the indicator should reset the value to the currently stored value in the options.
- [x] When viewing all settings at once & clicking a modifier indicator to reset the setting, it will collapse the shown settings to the last active settings tab, instead of keeping all tabs open.
- [x] It should sync when loading the page for the first time. E.g. if some new settings appear on startup which are not yet set in the file & "apply settings" is pressed there might be changes noted, which are not yet displayed by these indicators.
- [x] Make mobile settings not 2 column design, but tabs at the top, settings below.

After the merge the following got broken:
- [x] Search hiding nodes <-> new organization of DOM nodes in setting tabs
- [x] Show all pages shows the licenses as well
- [x] Resetting settings by clicking on the modification bar (this is due to me *ab*using the `_js` feature of the click event to skip event queueing (making the UI waaaay more responsive). It seems to have had changes in gradio which I need to investigate)
## Environment and Testing

Tested based on code branching from commit [89ffca0](https://github.com/vladmandic/automatic/pull/638/commits/89ffca0c8848255eddeb6246ac3f30cccfb4e5cc).
The colorations correspond to the 2 different states (where the colors depend on the theme's accent colors):
- Orange: Changed value which was not yet applied.
- Gray: Default value not yet stored.

Example Image

### CODE REVIEW

**Comment by vladmandic** [comment]
Looking forward to see this finished...

**Comment by EfourC** [comment]
I like your changes. Any idea if it's possible to make the empty space off the right side option text not clickable?

It's so easy to accidently toggle some random setting when just switching back to the window by clicking the blank area with the mouse.

If not, oh well!

MQLB59UqWf

**Comment by bryanray** [comment]
does it worked with original a1111 webui?

**Comment by Gegell** [comment]
> does it worked with original a1111 webui?

Currently I'm only developing based on vlad's branch. I need to check how hard it would be to transfer it over to auto's, but I think it shouldn't be too hard. I've put on the todo for now and will check once the last missing point is implemented.

**Comment by bryanray** [comment]
fantastic!

**Comment by vladmandic** [comment]
what's the status of this pr? its been in draft for a while now...

**Comment by Gegell** [comment]
> what's the status of this pr? its been in draft for a while now...

Yeah, sorry about that. Life has been a bit hectic for me the last couple weeks... :/ However I should have enough time this week to resolve the last outstanding issue I still have with it & bring it up to speed with the current main.

**Comment by Gegell** [comment]
After the merge the following got broken:
- [ ] Search hiding nodes <-> new organization of DOM nodes in setting tabs
- [ ] Resetting settings by clicking on the modification bar

**Comment by vladmandic** [comment]
i see pr is ready?
one quick comment - note that in js `onUiLoaded` callback is triggered a lot, so you don't want to execute function over and over, perhaps add a flag if its already initialized, just return?

**Comment by Gegell** [comment]
> i see pr is ready? 
Yeh finally ^^

> one quick comment - note that in js `onUiLoaded` callback is triggered a lot, so you don't want to execute function over and over, perhaps add a flag if its already initialized, just return?

Interesting, did not know how often it gets called... seems unintuitive :/ but yeah then a flag would then probably be a good solution ^^

**Comment by vladmandic** [comment]
code looks good.
i'll create a branch and merge this into a branch, just to test it a bit before merging to master - i don't trust myself with code review that much to merge into master directly :)

**Comment by Gegell** [comment]
sounds good to me. I hope I found all the edge cases ^^

**Pull request merged**
