### PR TITLE
Run pre-commit checks.

### PR DESCRIPTION
**Pull request by hameerabbasi**
## Description
Run linting and styling via pre-commit

## Notes
This will need to be a merge commit in order to keep the `.git-blame-ignore-revs` file valid. 😄 

I would recommend using Ruff instead of PyLint, as it incorporates many PyLint features already.

## Environment and Testing
All of these fixes are nice and automated. What's more, [CI can push a fix for you every time](https://pre-commit.ci/), less maintenance effort.

### CODE REVIEW

**Comment by vladmandic** [comment]
- `extensions-builtin` must be excluded
- some rules are just too much. for example it rewrote

```diff
- gr.Gallery(label='Output', show_label=False, elem_id='train_gallery').style(columns=1)
+ gr.Gallery(label="Output", show_label=False, elem_id="train_gallery").style(
+     columns=1
+ )
```

can we make it **minimally** intrusive to enable and then add rules that will be more intrustive?
but on first enable, it should catch only actuall errors.
then second rule can be to correct `'` into `"` (for example)

as it is, this is too masive to even look at.

**Comment by vladmandic** [comment]
disable black for now, we can revisit later.
for ruff, sdnext already has pyproject.toml that should be used automatically

**Comment by hameerabbasi** [comment]
Sorry I didn't get time to work on this yet -- I'll try to make future updates incremental, starting with Ruff.

**Comment by vladmandic** [comment]
sorry this got auto-closed because dev branch got deleted. please do resubmit once its ready.

**Pull request closed without merging**
