### PR TITLE
Compel parsing for SDXL.

### PR DESCRIPTION
**Pull request by hameerabbasi**
## Description

Based off of and supercedes #1900.

## Notes

I don't know what the hell I'm doing yet, I'll leave comments where I'm unsure about something.

## Environment and Testing

None, yet. Just cleaned up the code.

### CODE REVIEW

**Review by hameerabbasi — COMMENTED** [review]
One question.

**Comment by vladmandic** [comment]
Is this ready for review or still in draft? (If it's draft, can you mark it as such)

**Comment by AI-Casanova** [comment]
@vladmandic sorry, we're going to collaborate over on my PR, and I'll pull the tag when we're satisfied.

**Comment by vladmandic** [comment]
No worries. And you can keep the PR open (that way I can even take a look when I'm curious, but not bug you since it's not ready), just mark it as draft.

**Comment by hameerabbasi** [comment]
We moved the commits to #1900, if you want to take a look at the latest state you can do so there.

**Pull request closed without merging**
