### PR TITLE
Add uv pip as opt-in features

### PR DESCRIPTION
**Pull request by Yoinky3000**
## Description

Add `--uv` flag to opt-in to replacing `pip` with `uv pip`, able to improve the speed of installing by around 30% to 50%

Ubuntu:
* With uv
image
image

* Without uv
image
image

Windows:
* With uv
image
image

* Without uv
image
image

## Environment and Testing

Ubuntu 22.04 LTS Python 3.10
Windows 11 Python 3.10
Clean Install

### CODE REVIEW

**Comment by lbeltrame** [comment]
I had no idea what "uv" was, so for everyone else reading this PR, here's a link:

https://pypi.org/project/uv/

It's defined as

"An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common pip and pip-tools workflows."

**Comment by Yoinky3000** [comment]
> I had no idea what "uv" was, so for everyone else reading this PR, here's a link:
> 
> https://pypi.org/project/uv/
> 
> It's defined as
> 
> "An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common pip and pip-tools workflows."

yeah, a replacement for the default pip

**Comment by vladmandic** [comment]
i like idea of `uv` as standard pip is pretty bad tool no matter how you look at it. but `uv` is unproven and there is no chance to test compatibility over fully range of platforms supported by sdnext.

pr itself is nicely done - i'd love to merge it as an optional feature:
leave `pip` as default and use `uv` if `--uv` cmdflag is present.

**Comment by Yoinky3000** [comment]
> i like idea of `uv` as standard pip is pretty bad tool no matter how you look at it. but `uv` is unproven and there is no chance to test compatibility over fully range of platforms supported by sdnext.
> 
> pr itself is nicely done - i'd love to merge it as an optional feature: leave `pip` as default and use `uv` if `--uv` cmdflag is present.

just made a commit to make uv an opt-in feature, also added uv testing to github action

**Comment by vladmandic** [comment]
very nicely done!

one totally minor nitpick:
> log.info(f'{uvMode}Install: package="{arg.replace("install", "").replace("--upgrade", "").replace("--no-deps", "").replace("--force", "").replace("  ", " ").strip()}"')
 
to be inline with sdnext style, perhaps change to:
> log.info(f'Install: package="{arg.replace("install", "").replace("--upgrade", "").replace("--no-deps", "").replace("--force", "").replace("  ", " ").strip()}" mode={"uv" if uv else "pip"')

and remove:
> installer.log.info('Using "uv pip" instead of "pip" for packages installation')

**Comment by Yoinky3000** [comment]
@vladmandic I forgot to delete the line declaring uvMode
https://github.com/vladmandic/automatic/pull/3302/files#diff-b3ceed9306616c3f796c24f51d822762048d6032f4a4a0b290ac0e2d935eaaa1R242

**Comment by vladmandic** [comment]
i noticed, no worries, i'll clean it up.
pr is near-perfect, so not going to nitpick :)

**Pull request merged**
