### PR TITLE
Add support for --gradio-allowed-path

### PR DESCRIPTION
**Pull request by OuticNZ**
## Description

Add command line option --gradio-allowed-path.  This allows gradio to serve files from other paths as specified by the command line.   It's useful if you are using symbolic links.  It resolve this issue reported for sd-webui-depth-lib https://github.com/jexom/sd-webui-depth-lib/issues/29  

## Notes

More technical discussion about your changes go here, plus anything that a maintainer might have to specifically take a look at, or be wary of

## Environment and Testing

Tested on own test instance

### CODE REVIEW

**Comment by vladmandic** [comment]
i'm closing the PR as it touches too many files it shouldn't. but intention is good.
i've added `--allowed-paths` cli param and credited you in CHANGELOG.

**Comment by OuticNZ** [comment]
Thanks man.  Happy to take feedback - especially on your comment "it touches too many files it shouldn't".  There was probably any easier way to implement what I was looking for and well you did it.

**Comment by vladmandic** [comment]
its nothing major, its just that the PR includes CHANGELOG and README and those should never be in the itself. also, it includes requirements.txt, probably because it was not synced to latest version and it was updated since.

**Comment by OuticNZ** [comment]
Thanks.  Will take better care of those things next time.   Happy to help out where I can.

**Pull request closed without merging**
