### PR TITLE
Update webui.sh for ROCm

### PR DESCRIPTION
**Pull request by Aptronymist**
added AMD card detection and auto-HSA_OVERRIDE setting based on GPU

### CODE REVIEW

**Comment by vladmandic** [comment]
in a lack of better term, this is really "brittle" - executing external utility and then parsing its output in a shell script may cause equal amount of problems to those it solves. there are plenty of cases where rocminfo is either not in path or not behaving correctly, so this does not address those. and entire point of webui.sh is to create/activate venv and start python.
now we're re-adding dependencies. i get that this is a real problem for amd users, but this should really be handled inside rocm itself (it would be trivial for amd to sort this out).

i'm not sure if this should be added or not. plus how would this be tested?

**Comment by Aptronymist** [comment]
> in a lack of better term, this is really "brittle" - executing external utility and then parsing its output in a shell script may cause equal amount of problems to those it solves. there are plenty of cases where rocminfo is either not in path or not behaving correctly, so this does not address those. and entire point of webui.sh is to create/activate venv and start python. now we're re-adding dependencies. i get that this is a real problem for amd users, but this should really be handled inside rocm itself (it would be trivial for amd to sort this out).
> 
> i'm not sure if this should be added or not. plus how would this be tested?

I didn't expect this to be merged right in, but since I worked it up I figured I'd at least put it out here.

I did have one person test it so far and it worked fine, gave the expected result at least, and I *think* the script is supposed to gracefully handle there not being a rocminfo, still waiting to find more willing test ~~victims~~ ~~subjects~~ ~~dummies~~ volunteers, I expect more will be around in a few hours.

I see what you mean about it just handling the venv though, but I'm unsure what alternative there is. Perhaps this as a separate script for rocm users only?

**Comment by vladmandic** [comment]
ok, took a second look. this should not be in `webui.sh` - shell scripts are prone to breaking plus this would also need to be ported to webui.bat once torch-rocm is available there (i hope soon) plus it creates a bad precendent.

but - it fits nicely in `installer.py:check_torch()` - there is already `elif allow_rocm` so that rocminfo execution and setting of env variable can go there.

**Comment by Aptronymist** [comment]
> ok, took a second look. this should not be in `webui.sh` - shell scripts are prone to breaking plus this would also need to be ported to webui.bat once torch-rocm is available there (i hope soon) plus it creates a bad precendent.
> 
> but - it fits nicely in `installer.py:check_torch()` - there is already `elif allow_rocm` so that rocminfo execution and setting of env variable can go there.
> 
> https://github.com/vladmandic/automatic/blob/417ef540039e2d89a02cefb4fea2d767a5ba1380/installer.py#L314

Great, I'll take a look at it and submit a PR when I can.

**Pull request closed without merging**
