### PR TITLE
PowerShell launcher

### PR DESCRIPTION
**Pull request by em411**
## Description

This pull request deprecates the `webui.bat` batch script and introduces a new PowerShell script, `webui.ps1`, for installation. The change is intended to improve the user experience. The `README.md` has been updated to reflect this change and to direct users to use `webui.ps1` for installation.

## Notes

The `webui.bat` now contains a deprecation warning, alerting users to the upcoming transition and suggesting the use of `webui.ps1`. The warning is followed by a 10 second timeout to allow users to acknowledge the message.

image
---
This feature removes annoying `Terminate batch job (Y/N)?` prompt, providing a smoother and more user-friendly experience.

image
---
The `webui.ps1` script is developed to perform the same functions as the batch script to ensure a seamless transition. Error handling and environment setup are built into the PowerShell script to increase the robustness of the installation process.

## Environment and Testing

This was developed and tested on Windows 11 23H2 using PowerShell 5.1. Further testing on various other Windows platforms is recommended to confirm functionality and compatibility. The deprecation warning and the timeout in the batch script should also be verified to ensure that users are properly informed of the transition.

### CODE REVIEW

**Comment by vladmandic** [comment]
as it is, PS is still not a default shell in Windows.
and there are zero reasons to obsolete BAT that everyone is used to. not to mention it would break pretty much all wrappers that users have in place.

i would be willing to consider adding webui.ps1 in addition to webui.bat, but absolutely no chance of deprecation.
but even for that, you have to state why is ps1 better format for launcher? it cannot be just because its newer.

**Comment by em411** [comment]
You're right, I suggested deprecating webui.bat because I don't see the point of maintaining two launchers for the same system configuration. Just to clarify, my changes wouldn't break their code, but it would add 10 seconds to the boot process.

The default command line in Windows 11 as of version 22H2 (October 2022) is Windows Terminal, which runs PowerShell by default.

Ref: https://devblogs.microsoft.com/commandline/windows-terminal-is-now-the-default-in-windows-11/

Other benefits:
- Eliminates the need to confirm "Stop batch job (Y/N)?
- Better error handling,
- PowerShell 5.1 came with the Anniversary Update for Windows 10 in 2016.

If you're willing to accept ps1 as an additional launcher, I'll remove the deprecation message from webui.bat and roll back the changes in the wiki.

**Comment by vladmandic** [comment]
I'd be ok with that.
Also please test if it handles cmd line params if set via shortcut to ps1 launcher.

**Comment by em411** [comment]
Reverted changes in wiki and webui.bat.

Shortcut works fine, I've tested: 
Target: `powershell.exe -Command "D:\PycharmProjects\automatic\webui.ps1" --debug --quick`

image

**Pull request merged**
