### PR TITLE
Enable side loading of multiple Kohya-style LoRA for SDXL

### PR DESCRIPTION
**Pull request by AI-Casanova**
Multiple lora can now be added to prompt

New Options in settings under Diffusers

- kohya-apply: recommended, fastest pre-generation time
- kohya-merge: Slow loading time, potentially faster for large batches, not yet optimized for batch count
- Diffusers: Previous single LoRA implementation

xyz_grid-0529-sdXL_v10

### CODE REVIEW

**Comment by vladmandic** [comment]
i really like this pr - few nitpicks only:
- in `lora_diffusers.py`, any reason why there are two `import` sections?  
  one at the top of the file and one larger a bit lower  
- please translate non-english code comments to english  
- in `"diffusers_lora_loader": OptionInfo("default", "Diffusers LoRA loading variant", gr.Radio, lambda: {"choices": ['kohya-apply', 'kohya-merge', 'Diffusers']}),`  
  `default`` is not actually one of choices  
  and can we rename choices so they are more user friendly instead of technical?  
  maybe `basic apply`, `sequential apply`, `merge before apply`?  
- in your opinion, what should be default setting?  
  i understand that kohya-merge is a bit slower, but are there any benefits of default vs sequential (kohya-spply)? 
- can you add a sentence describing `diffusers_lora_loader` setting so i can add it to built-in hints?  
  (or directly add line in `html/locale_en.json`)

**Comment by AI-Casanova** [comment]
- The imports are a relic of the fact that the lower code is brought in from Koyha, they can be moved and 
translated.
- Diffusers is default/the old method, can be renamed to default
- kohya-apply is the recommended setting 
- Merge is a tiny bit faster to generate, but takes time to merge. Can likely be hidden, may possibly need to revisit it for extending to Lycoris when I concentrate on that after this one goes it. 
- Sure, I can figure out hints a bit later today

**Comment by vladmandic** [comment]
sounds good. what do you think about proposed names?

**Comment by AI-Casanova** [comment]
"Sequential apply" and "default" works great for me. 

Tool tipping default to say that it only works for a single LoRA and is not recommended though might be prudent. 

@hameerabbasi are you free to do some cleanup? I can review, but Mondays are busy at my day job and I don't want to keep Vlad waiting if he's ready.

**Comment by vladmandic** [comment]
merged to dev, if everything is ok, will merge to master.

**Pull request merged**
