### PR TITLE
Add missing check for empty tensor

### PR DESCRIPTION
**Pull request by ilikenwf**
## Description

This fixes one issue, the other is in k-diffusers; I'll put a pull in there too. Ran into this with tiled VAE...and I'm lazy so chatgpt did the work for me.

### CODE REVIEW

**Comment by ilikenwf** [comment]
k-diffusers: https://github.com/crowsonkb/k-diffusion/pull/65

**Comment by vladmandic** [comment]
chatgpt did a pretty good job :)

**Comment by ilikenwf** [comment]
> chatgpt did a pretty good job :)

I didn't feel like learning the tensorflow API, good to see it knew it well already...ha!

**Comment by vladmandic** [comment]
it didn't actually use any new api's it just rearranged existing code

**Comment by ilikenwf** [comment]
Yes, it was a pretty standard modification as we were blindly calling .min() without checking first if it was safe to do so...between my current job using a language that's arguably an "easier" language than previous, and GPT being available, I have trouble caring enough to trace where something's size is set, be it in code or documentation, when I can ask the robot to do it for me...haha

**Pull request merged**
