### PR TITLE
mobile css fixes

### PR DESCRIPTION
**Pull request by iDeNoh**
## Description

small number of fixes to make mobile usage a little easier

## Notes

added media query to detect devices with touchscreen and set --left-column to 100% rather than 500px
also set the slider input field to center justified instead of left justified as there were a small number of issues there

## Environment and Testing

tested in edge using device emulation, pixel 7, and desktop modes

### CODE REVIEW

**Comment by vladmandic** [comment]
```css
@media (hover: none) and (pointer: coarse)
```
interesting css selector. how does it behave on multi-input devices? e.g. notebook which has a trackpad and a touch screen.
and what about large size tablets (10+")? they are coarse, but i don't think we should set width to 100% on those.

**Comment by iDeNoh** [comment]
> ```css
> @media (hover: none) and (pointer: coarse)
> ```
> 
> interesting css selector. how does it behave on multi-input devices? e.g. notebook which has a trackpad and a touch screen. and what about large size tablets (10+")? they are coarse, but i don't think we should set width to 100% on those.

I hadn't considered tablet devices, I can do some testing when I get home and see how it effects large format screens and multi format devices. I had though about going off of aspect ratio + input device.

**Comment by vladmandic** [comment]
Maybe just based on width?
More than 1000px and go with default 500ppx, else 100%.

**Comment by iDeNoh** [comment]
Biggest issue that I can think of is most modern smart devices have a width well above 1000px, maybe there's a way to use pixel ratio instead.

**Comment by vladmandic** [comment]
Yeah, but they report smaller viewport dimensions or mobile browsing would look horrible everywhere.
Need to find which "width" is good to look at.

**Comment by iDeNoh** [comment]
Yeah, I just pulled up a list and am using it for reference, I've noticed a few other quirks that need to be worked out as well, I'll let you know when I've sorted it out.

**Comment by iDeNoh** [comment]
I've modified the media query to stop it affecting larger format displays, I went with 1080px as there are a few foldable devices that read above 1000px while closed. I also fixed a number of smaller issues, as well as the settings panel as it was cutting off content with the current configuration.

**Pull request merged**
