### PR TITLE
Safari/webkit fixes

### PR DESCRIPTION
**Pull request by eadnams22**
## Description

Should fix the results being pushed to the bottom of the page quite so soon, as well as extensions overflowing in to a hidden area in img2img.

## Notes

Added the inline style attribute from img2img_results to the css file and added !Important
changed the extension area to no longer use display:grid, which makes it flow in to the avaliable space correctly

This is my first pull request, so hope I did it right!

## Environment and Testing

Macos Safari
iPadOS Chrome (webkit)

### CODE REVIEW

**Comment by eadnams22** [comment]
Oh, for sure! first I’ll see if it’s even necessary on dev! Thanks!

**Comment by eadnams22** [comment]
There, think that did it.

**Comment by vladmandic** [comment]
looks good, one tiny thing - `!important`, not `!IMPORTANT` please :)

**Comment by eadnams22** [comment]
Noob question: Is there an easy way to change that without doing new commits and pull requests?

**Comment by vladmandic** [comment]
if you just change it on your fork, save and commit the pr should get automatically updated.
basically, as long as this pr is open, whatever changes you do on your fork will automatically be added to pr.

**Pull request merged**
