### PR TITLE
Intel ARC Support

### PR DESCRIPTION
**Pull request by Disty0**
## Description

Add Intel IPEX support for Intel ARC GPUs

## Notes

use --use-ipex command line option

## Environment and Testing

Arch Linux 
OneApi Basekit 2023.1
Intel ARC A770 16G

### CODE REVIEW

**Comment by vladmandic** [comment]
thanks, this is really welcome!
one concern is with `from modules import shared` added pretty much everywhere - it creates a lot of circular imports. any ideas how to minimize that?
otherwise, nice PR, even properly patched `setup.py`

**Comment by vladmandic** [comment]
one more thing, quite a few of scripts in `/cli` are standalone, they do not rely on core sd repo at all.
for example, `cli/random/dynamotest.py` is my dynamo test script, it should not import anything from core repo at all.
perhaps best not to patch `/cli` at all at the moment and once i refactor those, add ipex support as needed.

**Comment by vladmandic** [comment]
fyi, i've moved `--use-ipex` flag to installer directly as installer should not have dependency on modules.shared, that can lead to many issues if anything goes wrong. otherwise, nice job - thanks!

**Comment by Disty0** [comment]
Using --index-url causes torch version null error when installing PyTorch.

Changing --index-url to -f fixes it.

installer.py line 204:

`torch_command = os.environ.get('TORCH_COMMAND', 'torch==1.13.0a0+git6c9b55e torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.120+xpu --index-url https://developer.intel.com/ipex-whl-stable-xpu')`

to

`torch_command = os.environ.get('TORCH_COMMAND', 'torch==1.13.0a0+git6c9b55e torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.120+xpu -f https://developer.intel.com/ipex-whl-stable-xpu')`

**Comment by Disty0** [comment]
Also here is a screenshot with an Intel ARC A770 16G:

image

**Comment by vladmandic** [comment]
I'll check torch command.
Bit off topic, can you run benchmark from system info and submit it? Really curios...

**Comment by Disty0** [comment]
> I'll check torch command. Bit off topic, can you run benchmark from system info and submit it? Really curios...

I  get way less performance because of my poor CPU and mobo. Others should get around 8 it/s.
(I was getting 4 it/s with older sd forks while others was getting around 7.)

image

**Comment by vladmandic** [comment]
Actually, seems Arc gets going with higher parallel loads, you got 9its with batch size 4. Given the price point, that's not bad at all.

**Comment by vladmandic** [comment]
i've changed torch command as suggested.

**Comment by diffusersd** [comment]
how good it is compared to rx cards with rocm? 8it/s sounds really good. how is memory management within ipex?

**Comment by vladmandic** [comment]
you can look at all submitted records: <https://vladmandic.github.io/sd-extension-system-info/pages/benchmark.html>
it looks roughly on-par with 6700XT/6800XT with ROCm 5.4 (results with ROCm 5.2 are worse)

**Comment by Disty0** [comment]
> how good it is compared to rx cards with rocm? 8it/s sounds really good. how is memory management within ipex?

Here is the docs:

https://intel.github.io/intel-extension-for-pytorch/xpu/1.13.120+xpu/tutorials/api_doc.html#memory-management


I can generate up to 1920x1080 with split-attention or 2048x2048 (too slow to use) with sub-quad.
1920x1080 with other optimizations or no optimization needs around 150-250 MB extra VRAM than available.
Scaled-dot uses too much memory while running slower than other optimizations.
Arc A770 runs the fastest without any optimization at all.

**Comment by eneskuluk** [comment]
Sounds amazing thanks

**Comment by Disty0** [comment]
Current results after the last commits:
Others reported 7.8 it/s.
My results with my R5 1600X's slow single thread performance bottlenecking it:

image

**Comment by vladmandic** [comment]
That's roughly RTX3070 level, not bad...

**Comment by cyatarow** [comment]
I have some questions:

- Will this work on WSL?
- If yes, how fast and how large an image can it generate?

If I don't have to use a native Linux environment, I'd love to.

**Comment by vladmandic** [comment]
can you open a question in discussions instead of commenting on a closed commit?

**Comment by cyatarow** [comment]
OK. Here is the link: https://github.com/vladmandic/automatic/discussions/998

**Comment by TotalDay** [comment]
WSL Ubuntu

Ipexrun'ning launch.py...
/home/azer/automatic/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
File "/home/azer/automatic/venv/bin/ipexrun", line 8, in
sys.exit(main())
File "/home/azer/automatic/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 880, in main
launcher.launch(args)
File "/home/azer/automatic/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 447, in launch
numactl_available = self.is_numactl_available()
File "/home/azer/automatic/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 262, in is_numactl_available
r = subprocess.run(cmd, env=os.environ, stdout=subprocess.DEVNULL)
File "/usr/lib/python3.10/subprocess.py", line 501, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib/python3.10/subprocess.py", line 969, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'numactl'

**Comment by TotalDay** [comment]
You  broke WEBUI!!!!!!

**Pull request merged**
